# Generated by Django 4.1.7 on 2023-02-23 08:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Voiture', 'Voiture'), ('Moto', 'Moto'), ('Avion', 'Avion'), ('Bateau', 'Bateau')], default='Voiture', max_length=50)),
                ('jour', models.DateField(default=datetime.datetime.now)),
                ('heure', models.CharField(choices=[('9h', '9h'), ('10h', '10h'), ('11h', '11h'), ('12h', '12h'), ('13h', '5 PM'), ('14h', '5:30 PM'), ('15h', '15h'), ('16h', '16h'), ('17h', '17h'), ('18h', '18h')], default='3 PM', max_length=10)),
                ('temps_commande', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
